name: Custom Workflow
on:
  push:
    branches: [develop]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 18

      - name: run npm install
        run: npm install
        
      - name: test
        run: npm test
